### ISSUE TITLE
Power off speakers at night

### ISSUE THREAD

**Issue by stephanfo** [VanVan/phantom-remote-control#4]
Thanks VanVan for your work on this repo.

Recently I've discovered the possibility to make Phantoms sleeping directly from the app (before I had to pressed 4sec the button on the back of each one).
I would like to automatize the sleep mode every night (energy consomption concern). Do you know if it is possible using your method?

Thanks,

**Comment by VanVan** [comment]
Hello,
The idea is good indeed.
I personally didn't update my devaliet to DOS2, because then it's not possible to control the devialet from a Windows/Linux application, but only from Android/iOS.
So I can't check by myself the DOS1 version I'm using doesn't offer a standby feature.
However, if you can send me the network traffic communication allowing the application to control the devialet dans sleeping, I could deduce how it works.

**Comment by stephanfo** [comment]
Thanks for your reply. I dug further into it, and maybe it’s better to wait a bit. DOS 2.14 comes with a documented API, and 2.16 should implement the API power off feature. Just FYI the official webpage with the pdf documentation. 

https://help.devialet.com/hc/en-us/articles/4415207423378-Phantom-s-documentation-for-piloting-them-via-IP

**Comment by VanVan** [comment]
I just looked indeed, good news, the Phantom speaker is available since 2015, it will have taken 7 years, it's long, but I will finally be able to update to DOS2!

**Comment by stephanfo** [comment]
Agreed, very good speakers when it comes to sound quality & hardware, but software could have been way better. Now the point is when the 2.16 will be out...
